FROM node:20-alpine

WORKDIR /app

# native build deps for better-sqlite3
RUN apk add --no-cache python3 make g++

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 1337

CMD ["npm","run","develop"]

